version: '3.9'

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=productcatalog
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: